version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  sh1:
    networks:
      splunknet:
        aliases:
          - sh1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: sh1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1,idx2
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089

  idx1:
    networks:
      splunknet:
        aliases:
          - idx1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1,idx2
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089

  idx2:
    networks:
      splunknet:
        aliases:
          - idx2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1,idx2
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089

  hf1:
    networks:
      splunknet:
        aliases:
          - hf1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: hf1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1,idx2
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_ROLE=splunk_heavy_forwarder
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089

  hf2:
    networks:
      splunknet:
        aliases:
          - hf2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: hf2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1,idx2
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_ROLE=splunk_heavy_forwarder
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089
      
  dmc:
    networks:
      splunknet:
        aliases:
          - dmc
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: dmc
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1,idx2
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_ROLE=splunk_monitor
      - SPLUNK_LICENSE_URI
      - SPLUNK_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089