version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  uf1:
    networks:
      splunknet:
        aliases:
          - uf1
    image: ${UF_IMAGE:-splunk/universalforwarder:latest}
    hostname: uf1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - DEBUG=true
      - SPLUNK_ADD=udp 1514,monitor /var/log/*
      - SPLUNK_PASSWORD
    ports:
      - 8089

  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - DEBUG=true
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089

  dmc:
    networks:
      splunknet:
        aliases:
          - dmc
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: dmc
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_ROLE=splunk_monitor
      - SPLUNK_LICENSE_URI
      - SPLUNK_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089
