version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  appserver:
    networks:
      splunknet:
        aliases:
          - appserver
    image: nwang92/nginx-mitm
    hostname: appserver
    ports:
      - 80
    volumes:
      - ../tests/fixtures:/www/data

  uf1:
    networks:
      splunknet:
        aliases:
          - uf1
    image: ${UF_IMAGE:-splunk/universalforwarder:latest}
    hostname: uf1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
      - SPLUNK_APPS_URL
      - DEBUG=true
    ports:
      - 8089
