version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  idx3:
    networks:
      splunknet:
        aliases:
          - idx3
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx3
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_URL=sh1,sh2
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_IDXC_PASS4SYMMKEY=asdf1234
      - SPLUNK_LICENSE_URI
      - SPLUNK_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089
