version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  cm1:
    networks:
      splunknet:
        aliases:
          - cm1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: cm1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_cluster_master
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx1:
    networks:
      splunknet:
        aliases:
          - idx1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx2:
    networks:
      splunknet:
        aliases:
          - idx2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx3:
    networks:
      splunknet:
        aliases:
          - idx3
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx3
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults
  